/**
 * HTTP client for the Crema FastAPI backend.
 *
 * The MCP server is a thin wrapper — it shells out to the same
 * endpoints the web UI uses, with the same admin bearer token. This
 * means every MCP tool call benefits from the same auth, the same
 * route handlers, the same hooks. No logic duplicated, no risk of
 * the MCP path silently diverging from what an admin would get
 * through the UI.
 *
 * Configuration via env vars:
 *   CREMA_API_BASE        default: http://localhost:8000
 *   CREMA_ADMIN_TOKEN     required: the admin session token
 *   CREMA_AGENT_IDENTITY  default: claude-code@local
 *                         (e.g. `claude-sonnet-4-6@anthropic`,
 *                          `llama-3.3-70b@macstudio.local`)
 *   CREMA_SESSION_ID      default: <auto-generated per server boot>
 */

const API_BASE = (process.env.CREMA_API_BASE || "http://localhost:8000").replace(/\/$/, "");
const TOKEN = process.env.CREMA_ADMIN_TOKEN || "";
const AGENT_IDENTITY = process.env.CREMA_AGENT_IDENTITY || "claude-code@local";
const SESSION_ID = process.env.CREMA_SESSION_ID || `mcp-${Date.now().toString(36)}`;

export class CremaApiError extends Error {
  constructor(public status: number, public body: string, message: string) {
    super(message);
    this.name = "CremaApiError";
  }
}

export interface RequestOptions {
  method?: "GET" | "POST" | "PUT" | "DELETE";
  body?: unknown;
  query?: Record<string, string | number | undefined>;
}

export async function call<T = unknown>(
  path: string,
  opts: RequestOptions = {},
): Promise<T> {
  if (!TOKEN) {
    throw new Error(
      "CREMA_ADMIN_TOKEN is not set. Mint one via login or read from the session table; pass it as CREMA_ADMIN_TOKEN in the MCP server env.",
    );
  }
  let url = `${API_BASE}/api${path.startsWith("/") ? path : "/" + path}`;
  if (opts.query) {
    const qs = new URLSearchParams();
    for (const [k, v] of Object.entries(opts.query)) {
      if (v !== undefined && v !== null) qs.set(k, String(v));
    }
    const qstr = qs.toString();
    if (qstr) url += `?${qstr}`;
  }
  const headers: Record<string, string> = {
    Authorization: `Bearer ${TOKEN}`,
    Accept: "application/json",
  };
  const init: RequestInit = { method: opts.method || "GET", headers };
  if (opts.body !== undefined) {
    headers["Content-Type"] = "application/json";
    init.body = JSON.stringify(opts.body);
  }
  const resp = await fetch(url, init);
  const text = await resp.text();
  if (!resp.ok) {
    let detail = text.slice(0, 500);
    try {
      const j = JSON.parse(text);
      detail = j.detail ?? detail;
    } catch {
      /* ignore */
    }
    throw new CremaApiError(
      resp.status,
      text,
      `${init.method} ${path} → ${resp.status}: ${detail}`,
    );
  }
  if (!text) return undefined as T;
  return JSON.parse(text) as T;
}

export function unwrap<T = unknown>(envelope: unknown): T {
  // FastAPI responses are { data, meta }. Strip the envelope.
  if (envelope && typeof envelope === "object" && "data" in (envelope as any)) {
    return (envelope as any).data as T;
  }
  return envelope as T;
}

export const identity = { agent: AGENT_IDENTITY, session: SESSION_ID };
